spring.application.name=EMS

spring.data.mongodb.uri=mongodb://localhost:27017/ems_db

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG

#Spring Security JWT
jwt.SecretKey=138127tqgqdfqs87dtqw87dtqwdh1ey2r38721t2813g21f21iyer1287
jwt.expriation=86400000